dist: trusty
language: node_js

before_script: 
  - yarn
script:
  - yarn build

before_deploy:
  - cd build
  - tar -cvf smackworks-website-${TRAVIS_BUILD_ID}-${TRAVIS_BUILD_NUMBER}.tar.gz ./
  - cd ..

deploy:
  provider: releases
  api_key: "3ceead1c7d8599575c632bccdd253b58337bce44"
  file: build/smackworks-website-${TRAVIS_BUILD_ID}-${TRAVIS_BUILD_NUMBER}.tar.gz
  skip_cleanup: true
  on:
    tags: true

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
