sudo: required
services:
  - docker
env:
  global:
    - ORG=smackzter
    - IMAGE_NAME=smackworks
    - REGISTRY_USER=smackzter
    - REGISTRY_PASS=pnk45yrc

before_script:
  - docker pull "${ORG}/${IMAGE_NAME}" || true
script:
  - docker build --pull --cache-from "${ORG}/${IMAGE_NAME}" --tag "${ORG}/${IMAGE_NAME}" .

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push "${ORG}/${IMAGE_NAME}"
  on:
    branch: master

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
